Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Models/ViewModel/AddProduitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BusinessLayer.MonProjet;
using Modele.MonProjet.Entities;

namespace WebApplication.Models.ViewModel
{
    public class AddProduitViewModel
    {
        public Produit produit { get; set; }

        public List<Categorie> categories { get; set; }

        public BusinessLayerManager blm = BusinessLayerManager.Instance;

        public AddProduitViewModel()
        {
            this.categories = blm.GetAllCategorie();
        }

        public AddProduitViewModel(Produit p)
        {
            this.produit = p;
            this.categories = blm.GetAllCategorie();
        }

    }
}

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Models/ViewModel/ProduitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BusinessLayer.MonProjet;
using Modele.MonProjet.Entities;

namespace WebApplication.Models.ViewModel
{
    public class ProduitViewModel
    {
        public List<Produit> Produits { get; set; }

        public List<Commande> Commandes { get; set; }

        public BusinessLayerManager blm = BusinessLayerManager.Instance;

        public ProduitViewModel()
        {
            this.Produits = blm.GetAllProduit();
            this.Commandes = blm.GetAllCommande();
        }

        public ProduitViewModel(string searchQuery)
        {
            if (searchQuery != null)
            {
                int result = 0;
                Int32.TryParse(searchQuery, out result);

                this.Produits = blm.GetAllProduit()
                                .FindAll(p => p.Id == result
                                          || p.Code == result 
                                          || p.Description.ToLower() == searchQuery.ToLower()
                                          || p.Libelle.ToLower() == searchQuery.ToLower()
                                          || p.Prix == result
                                          || p.Stock == result
                                          || p.Categorie.Libelle == searchQuery);

                this.Commandes = blm.GetAllCommande()
                                 .FindAll(c => c.Id == result
                                            || c.Observation.ToLower() == searchQuery.ToLower());
            }
            else
            {
                this.Produits = new List<Produit>();
                this.Commandes = new List<Commande>();
            }
        }

    }
}

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Controllers/AddController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.MonProjet;
using Modele.MonProjet.Entities;
using WebApplication.Models.ViewModel;

namespace WebApplication.Controllers
{
    public class AddController : Controller
    {
        [HttpPost]
        public ActionResult HandleForm(AddProduitViewModel p)
        {
            BusinessLayerManager blm = BusinessLayerManager.Instance;

            blm.AjouterProduit(p.produit);
                     
            return RedirectToAction("Index", "Home");
        }

    }
}

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Controllers/EditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.MonProjet;
using Modele.MonProjet.Entities;
using WebApplication.Models.ViewModel;

namespace WebApplication.Controllers
{
    public class EditController : Controller
    {
        [HttpPost]
        public ActionResult HandleForm(AddProduitViewModel p)
        {
            BusinessLayerManager blm = BusinessLayerManager.Instance;

            p.produit.Categorie = p.categories.Find(c => c.Id == p.produit.CategorieId);

            blm.ModifierProduit(p.produit);
          
            return RedirectToAction("Index", "Home");
        }

    }
}

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.MonProjet;
using Modele.MonProjet.Entities;
using WebApplication.Models.ViewModel;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ProduitViewModel produitViewModel = new ProduitViewModel();
            return View(produitViewModel);
        }

        public ActionResult Detail(int id)
        {
            BusinessLayerManager blm = BusinessLayerManager.Instance;

            Produit p = blm.GetProduit(id);

            return View(p);
        }

        public ActionResult Add()
        {
            AddProduitViewModel addproduitViewModel = new AddProduitViewModel();
            return View("../Add/Add",addproduitViewModel);
        }

        public ActionResult Edit(int id)
        {
            BusinessLayerManager blm = BusinessLayerManager.Instance;
            Produit pToEdit = blm.GetProduit(id);

            AddProduitViewModel addproduitViewModel = new AddProduitViewModel(pToEdit);
            return View("../Edit/Edit",addproduitViewModel);
        }

        public ActionResult Delete(int id)
        {
            BusinessLayerManager blm = BusinessLayerManager.Instance;
            blm.SupprimerProduit(id);

            ProduitViewModel produitViewModel = new ProduitViewModel();
        
            return View("Index", produitViewModel);
        }


        public ActionResult Search(String search)
        {
            ProduitViewModel produitViewModel = new ProduitViewModel(search);
            return View(produitViewModel);
        }


        public ActionResult DetailCommande(int id) 
        {
            BusinessLayerManager blm = BusinessLayerManager.Instance;

            Commande c = blm.GetAllCommande().Find(commande=> commande.Id == id);

            return View(c);
        }
    }
}

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Controllers/ListProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.MonProjet;
using Modele.MonProjet.Entities;
using WebApplication.Models.ViewModel;

namespace WebApplication.Controllers
{
    public class ListProductController : Controller
    {
        
        public ActionResult Index()
        {
            ProduitViewModel produitViewModel = new ProduitViewModel();
            return View(produitViewModel);
        }

        public ActionResult Detail(int id)
        {
            BusinessLayerManager blm = BusinessLayerManager.Instance;

            Produit p = blm.GetProduit(id);

            return View(p);
        }

        public ActionResult Add()
        {
            AddProduitViewModel addproduitViewModel = new AddProduitViewModel();
            return View(addproduitViewModel);
        }

    }
}

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/Add/Add.cshtml
@model WebApplication.Models.ViewModel.AddProduitViewModel
@{
    ViewBag.Title = "Add";
    List<SelectListItem> items = new List<SelectListItem>();
    foreach (var categorie in Model.categories)
    {
        items.Add(new SelectListItem { Value = categorie.Id.ToString(), Text = categorie.Libelle });
    }
}

<div class="add_div">

    @using (Html.BeginForm("HandleForm", "Add"))
    {

        <div class="form-group">
            @Html.LabelFor(p => p.produit.Code)
            <div>@Html.TextBoxFor(p => p.produit.Code, new { @class = "form-control" })</div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Description)
            <div>
                @Html.TextBoxFor(p => p.produit.Description, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Libelle)
            <div>
                @Html.TextBoxFor(p => p.produit.Libelle, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Prix)
            <div>
                @Html.TextBoxFor(p => p.produit.Prix, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Stock)
            <div>
                @Html.TextBoxFor(p => p.produit.Stock, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Categorie)
            <div>
                @Html.DropDownListFor(p => p.produit.CategorieId, items, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group form-check">
                @Html.LabelFor(p => p.produit.Actif)
                <div>
                    @Html.CheckBoxFor(p => p.produit.Actif, new { @class = "form-check-input" })
              </div>
        </div>
            <button type="submit" class="btn btn-primary">Ajouter</button>
            }

        </div>

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/Edit/Edit.cshtml
@model WebApplication.Models.ViewModel.AddProduitViewModel
@{
    ViewBag.Title = "Edit";
    List<SelectListItem> items = new List<SelectListItem>();
    foreach (var categorie in Model.categories)
    {
        items.Add(new SelectListItem { Value = categorie.Id.ToString(), Text = categorie.Libelle });
    }
}

<div class="add_div">

    @using (Html.BeginForm("HandleForm", "Edit"))
    {
        <div style="display: none;" class="form-group">
            @Html.LabelFor(p => p.produit.Id)
            <div>@Html.TextBoxFor(p => p.produit.Id, new { @class = "form-control" })</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(p => p.produit.Code)
            <div>@Html.TextBoxFor(p => p.produit.Code, new { @class = "form-control" })</div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Description)
            <div>
                @Html.TextBoxFor(p => p.produit.Description, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Libelle)
            <div>
                @Html.TextBoxFor(p => p.produit.Libelle, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Prix)
            <div>
                @Html.TextBoxFor(p => p.produit.Prix, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Stock)
            <div>
                @Html.TextBoxFor(p => p.produit.Stock, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.produit.Categorie)
            <div>
                @Html.DropDownListFor(p => p.produit.CategorieId, items, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group form-check">
            @Html.LabelFor(p => p.produit.Actif)
            <div>
                @Html.CheckBoxFor(p => p.produit.Actif, new { @class = "form-check-input" })
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Valider</button>
    }

</div>

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/Home/Detail.cshtml
@model Modele.MonProjet.Entities.Produit
@{
    ViewBag.Title = "Detail";
}

<div class="detail_div">
    @if (Model != null)
    {
        <div style="text-align: center;">
            ID : @Model.Id
        </div>

        <div class="data_div">
            <div class="detail_flex_div">
                <div>Code</div>  <div>@Model.Code</div>
            </div>
            <div  class="detail_flex_div">
                <div>Description</div>   <div>@Model.Description</div>
            </div>
            <div class="detail_flex_div">
                <div>Libelle</div>  <div>@Model.Libelle</div>
            </div>
            <div class="detail_flex_div">
                <div>Prix</div>  <div>@Model.Prix EUR</div>
            </div>
            <div class="detail_flex_div">
                <div>Stock</div>  <div>@Model.Stock</div>
            </div>
        </div>
    }

</div>

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/Home/DetailCommande.cshtml
@model Modele.MonProjet.Entities.Commande
@{
    ViewBag.Title = "Detail Commande";
}

<div class="detail_div">
    @if (Model != null)
    {
        <div style="text-align: center;">
            ID : @Model.Id
        </div>

        <div class="data_div">
            <div class="detail_flex_div">
                <div>Date</div>  <div>@Model.DateCommand</div>
            </div>
            <div  class="detail_flex_div">
                <div>Observation</div>   <div>@Model.Observation</div>
            </div>
            <div class="detail_flex_div">
                <div>Statut</div>  <div>@Model.Statut</div>
            </div>
            <div class="detail_flex_div">
                <div>Client</div>  <div>@Model.Client</div>
            </div>
        </div>
    }

</div>

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/Home/Index.cshtml
@model WebApplication.Models.ViewModel.ProduitViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="row body_home">

    <div class="custom_card">
        <h3>Commandes</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Observation</th>
                    <th scope="col">Statut</th>
                    <th scope="col">DateCommand</th>
                    <th scope="col">Client</th>
                </tr>
            </thead>

            <tbody>

                @foreach (var c in Model.Commandes)
                {
                <tr>
                    <td> <a href="/Home/DetailCommande/@c.Id"> @c.Id </td>
                    <td> <a href="/Home/DetailCommande/@c.Id"> @c.Observation</td>
                    <td> <a href="/Home/DetailCommande/@c.Id"> @c.Statut</td>
                    <td> <a href="/Home/DetailCommande/@c.Id"> @c.DateCommand</td>
                    <td> <a href="/Home/DetailCommande/@c.Id"> @c.Client</td>
                </tr>
                }

            </tbody>
        </table>
    </div>

    <div class="custom_card">
        <h3>Produits</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Code</th>
                    <th scope="col">Description</th>
                    <th scope="col">Libelle</th>
                    <th scope="col">Prix</th>
                    <th scope="col">Stock</th>
                    <th scope="col">Actif</th>
                </tr>
            </thead>

            <tbody>

                @foreach (var p in Model.Produits)
                {
                <tr id="products" class="tr_table">
                    <td> <a href="/Home/Detail/@p.Id"> @p.Id </td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Code</td>
                    <td> <a href="/Home/Detail/@p.Id"> @p.Description</td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Libelle</td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Prix</td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Stock</td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Actif</td>
                    <td id="buttons" class="action_button_td">
                        <button onclick="location.href='@Url.Action("Delete", "Home")'" type="button" class="btn btn-danger action_button">Delete</button>
                        <button onclick="location.href='@Url.Action("Edit", "Home", new { id = @p.Id })'" type="button" class="btn btn-success action_button">Edit</button>
                    </td>
                </tr>
                }

            </tbody>
        </table>
    </div>


    </div>

    <script type="text/javascript">

    </script>

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/Home/ListProduct.cshtml
@model WebApplication.Models.ViewModel.ProduitViewModel
@{
    ViewBag.Title = "Products List";
}

<div class="row body_produits">

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Code</th>
                <th scope="col">Description</th>
                <th scope="col">Libelle</th>
                <th scope="col">Prix</th>
                <th scope="col">Stock</th>
            </tr>
        </thead>

        <tbody>

            @foreach (var p in Model.Produits)
            {
                <tr>
                    <td> <a href="/Home/Detail/@p.Id"> @p.Id </td>
                    <td> <a href="/Home/Detail/@p.Id"> @p.Code</td>
                    <td> <a href="/Home/Detail/@p.Id"> @p.Description</td>
                    <td> <a href="/Home/Detail/@p.Id"> @p.Libelle</td>
                    <td> <a href="/Home/Detail/@p.Id"> @p.Prix</td>
                    <td> <a href="/Home/Detail/@p.Id"> @p.Stock</td>
                </tr>
            }

        </tbody>
    </table>


</div>

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/Home/Search.cshtml
@model WebApplication.Models.ViewModel.ProduitViewModel
@{
    ViewBag.Title = "Search Page";
}

<div class="row body_home">

    <h3>Résultat Recherche</h3>

    @if (Model.Commandes != null && Model.Commandes.Count > 0)
    {
        <div class="custom_card">
            <h3>Commandes</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Observation</th>
                        <th scope="col">Statut</th>
                        <th scope="col">DateCommand</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach (var c in Model.Commandes)
                    {
                        <tr>
                            <td> <a href="/Home/Detail/@c.Id"> @c.Id </td>
                            <td> <a href="/Home/Detail/@c.Id"> @c.Observation</td>
                            <td> <a href="/Home/Detail/@c.Id"> @c.Statut</td>
                            <td> <a href="/Home/Detail/@c.Id"> @c.DateCommand</td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    }

    @if (Model.Produits != null && Model.Produits.Count > 0)
    {    <div class="custom_card">
            <h3>Produits</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Code</th>
                        <th scope="col">Description</th>
                        <th scope="col">Libelle</th>
                        <th scope="col">Prix</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Actif</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach (var p in Model.Produits)
                    {
                        <tr id="products" class="tr_table">
                            <td> <a href="/Home/Detail/@p.Id"> @p.Id </td>
                            <td> <a href="/Home/Detail/@p.Id">@p.Code</td>
                            <td> <a href="/Home/Detail/@p.Id"> @p.Description</td>
                            <td> <a href="/Home/Detail/@p.Id">@p.Libelle</td>
                            <td> <a href="/Home/Detail/@p.Id">@p.Prix</td>
                            <td> <a href="/Home/Detail/@p.Id">@p.Stock</td>
                            <td> <a href="/Home/Detail/@p.Id">@p.Actif</td>
                            <td id="buttons" class="action_button_td">
                                <button onclick="location.href='@Url.Action("Delete", "Home")'" type="button" class="btn btn-danger action_button">Delete</button>
                                <button onclick="location.href='@Url.Action("Edit", "Home", new { id = @p.Id })'" type="button" class="btn btn-success action_button">Edit</button>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    }

</div>

    <script type="text/javascript">

    </script>

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/ListProduct/Index.cshtml
@model WebApplication.Models.ViewModel.ProduitViewModel
@{
    ViewBag.Title = "List product";
}

<div class="row body_home">

    <div class="custom_card">
        <h3>Produits</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Code</th>
                    <th scope="col">Description</th>
                    <th scope="col">Libelle</th>
                    <th scope="col">Prix</th>
                    <th scope="col">Stock</th>
                    <th scope="col">Actif</th>
                </tr>
            </thead>

            <tbody>

                @foreach (var p in Model.Produits)
                {
                <tr id="products" class="tr_table">
                    <td> <a href="/Home/Detail/@p.Id"> @p.Id </td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Code</td>
                    <td> <a href="/Home/Detail/@p.Id"> @p.Description</td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Libelle</td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Prix</td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Stock</td>
                    <td> <a href="/Home/Detail/@p.Id">@p.Actif</td>
                    <td id="buttons" class="action_button_td">
                        <button onclick="location.href='@Url.Action("Delete", "Home", new { id = @p.Id })'" type="button" class="btn btn-danger action_button">Delete</button>
                        <button onclick="location.href='@Url.Action("Edit", "Home", new { id = @p.Id })'" type="button" class="btn btn-success action_button">Edit</button>
                    </td>
                </tr>
                }

            </tbody>
        </table>
    </div>


    </div>

Ecommerce.SEVIK.DETAXISDUPOET/WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - E-Commerce App ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header logo_title">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("E-Commerce App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand logo" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="li_navbar">

                        <input placeholder="Recherchez quelque chose" class="input_search" type="text" name="search" id="search" value="" />
                        @Html.ActionLink("Search", "Search", "Home", new { search = "xxx" }, new { @class = "link" })

                        <script>
                            $(function () {
                                $('.link').click(function () {
                                    var search = $("#search").val();
                                    this.href = this.href.replace("xxx", search);
                                });
                            });
                        </script>
                    </li>
                    <li>@Html.ActionLink("Liste des produits", "Index", "ListProduct")</li>
                    <li>@Html.ActionLink("Ajouter un produit", "Add", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BY SEVIK & DE TAXIS</p>
        </footer>
    </div>

 
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>